[article]
title = "Pelikan Segcache"
author = "Juncheng Yang"
date = "October 1, 2021"
tags = ["caching", "systems", "performance", "memory-management"]
abstract = "In collaboration with Carnegie Mellon University, Twitter is building Pelikan's next generation of storage backend, which enables high memory efficiency, high throughput, and scalability for workloads that are primarily small objects and widely use TTL (time-to-live)."

