name: Build Articles and Index

on:
  push:
    branches:
      - main
    paths:
      - 'articles/**'
      - 'scripts/**'
  workflow_dispatch:  # Allow manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: |
          pip install -e .
      
      - name: Convert markdown to HTML
        run: |
          python scripts/convert_md.py
      
      - name: Build index pages
        run: |
          python scripts/build_index.py
      
      - name: Check for changes
        id: check_changes
        run: |
          git diff --exit-code || echo "changes=true" >> $GITHUB_OUTPUT
      
      - name: Commit and push changes
        if: steps.check_changes.outputs.changes == 'true'
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add -A
          git commit -m "Auto-generate HTML and index pages [skip ci]"
          git push

